test: &default

  # Credentials for REST APIs
  client_id: AagTS61IFV9dL5gJ9KdNX7WE2Cb8sb1NrmGf4UVBP6qbQYe6E1f9ctEiAuIXhrzOfBeE4szp96rzVJPR
  client_secret: EGtvPsXVhnWiFDcSeI4OBL1yr7WJ7wS777y4NVirBU8M5tq_Bx2Dzh5wezjwp6Q2Lx-zel4Meh6gVYhm

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: 
  password: 
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: nkilleen@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
  client_id: AdQOAbV5oQNYncigLkCCIvyJ4anOrNLHbOIZe7pzPeLni3g9hwDxH3gORKu95hj1hxA4boozQsmonlXt
  client_secret: EKrlyRICWPUcNBA2SWvvepqZMUv8Dx8MKBqw4bZJYU_CfqokLGHCNx6F4wC9-qU_XorcaUBaO0JpurrC
